# Generated by Django 5.0.6 on 2024-06-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('definitions', '0002_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.title'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='definitions.title'),
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
