# Generated by Django 5.0.6 on 2024-06-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_skill_title_alter_customuser_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
