# Generated by Django 5.0.6 on 2024-06-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_of_user',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='type of user'),
            preserve_default=False,
        ),
    ]
