# Generated by Django 5.0.6 on 2024-06-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_type_of_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('hours', models.IntegerField()),
                ('expiration_date', models.DateTimeField(default=False, verbose_name='expiration date')),
            ],
        ),
    ]
