# Generated by Django 5.0.6 on 2024-06-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Upper Intermediate'), (5, 'Advanced')]),
        ),
    ]
