# Generated by Django 5.0.6 on 2024-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_usercertificate_expiration_date_userexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='connection',
            field=models.CharField(blank=True, max_length=50, verbose_name='connection'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='github_link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='twitter_link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='instagram_link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='investment_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='linkedin_link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sector',
            field=models.CharField(blank=True, max_length=50, verbose_name='sector'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state_region',
            field=models.CharField(blank=True, max_length=50, verbose_name='state_region'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='zip_code'),
        ),
    ]
