# Generated by Django 5.0.6 on 2024-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='twitter_link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='facebook_link'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='github_link'),
        ),
    ]
