# Generated by Django 5.0.6 on 2024-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_twitter_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='investment_amount',
            field=models.IntegerField(null=True),
        ),
    ]
