# Generated by Django 5.0.6 on 2024-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title_experience',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='title_experience'),
        ),
    ]
