# Generated by Django 5.0.6 on 2024-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_title_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.IntegerField(choices=[(1, 'Preschool'), (2, 'Primary School'), (3, 'Lower Secondary School'), (4, 'Upper Secondary School'), (5, 'Higher Education')], default=1),
            preserve_default=False,
        ),
    ]
