# Generated by Django 5.0.6 on 2024-07-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prefered_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='prefered_title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefered_title_experience',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='prefered_title_experience'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='education_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Preschool'), (2, 'Primary School'), (3, 'Lower Secondary School'), (4, 'Upper Secondary School'), (5, 'Higher Education')]),
        ),
    ]
