# Generated by Django 5.0.6 on 2024-07-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_prefered_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='competitors_project',
            field=models.CharField(blank=True, max_length=50, verbose_name='competitors_project'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description_project',
            field=models.CharField(blank=True, max_length=250, verbose_name='description_project'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='documents_project',
            field=models.FileField(blank=True, null=True, upload_to='documents_project/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interested_areas',
            field=models.CharField(blank=True, max_length=50, verbose_name='interested_areas'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title_project',
            field=models.CharField(blank=True, max_length=50, verbose_name='title_project'),
        ),
    ]
