# Generated by Django 5.0.6 on 2024-07-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_competitors_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_public_profile',
            field=models.CharField(blank=True, max_length=50, verbose_name='is_public_profile'),
        ),
    ]
