# Generated by Django 5.0.6 on 2024-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_customuser_is_public_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="about_me",
            field=models.TextField(blank=True, null=True, verbose_name="about me"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="education_level",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Preschool"),
                    (2, "Primary School"),
                    (3, "Lower Secondary School"),
                    (4, "Upper Secondary School"),
                    (5, "Higher Education"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="interested_areas",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="interested_areas"
            ),
        ),
    ]
