# Generated by Django 5.0.6 on 2024-07-12 15:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cv_link',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.CustomUser.user_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='documents_project',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.CustomUser.user_directory_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.CustomUser.user_directory_path),
        ),
    ]
