# Generated by Django 5.0.6 on 2024-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customuser_cv_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, verbose_name='status'),
        ),
    ]
