# Generated by Django 5.0.6 on 2024-09-02 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotesForHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_owner_user_id', models.IntegerField(blank=True, null=True)),
                ('note_date', models.DateField()),
                ('note_detail', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
