# Generated by Django 5.0.6 on 2024-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_usernotesforhr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='investment_amount',
            field=models.TextField(blank=True, null=True),
        ),
    ]
