# Generated by Django 5.0.6 on 2024-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0004_userprofiletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapsJuniflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_project_id', models.IntegerField()),
                ('jf_project_id', models.IntegerField()),
            ],
        ),
    ]
