# Generated by Django 5.0.6 on 2024-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0005_projectmapsjuniflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMapsJuniflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_user_id', models.IntegerField()),
                ('jf_user_id', models.IntegerField()),
            ],
        ),
    ]
