# Generated by Django 5.0.6 on 2024-06-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0006_usermapsjuniflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('oran', models.IntegerField()),
            ],
        ),
    ]
