# Generated by Django 5.0.6 on 2024-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0008_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('type_of_menu', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('main_menu_id', models.IntegerField()),
            ],
        ),
    ]
