# Generated by Django 5.0.6 on 2024-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0009_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
