# Generated by Django 5.0.6 on 2024-06-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0010_menu_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('project_id', models.IntegerField()),
                ('menu_id', models.IntegerField()),
            ],
        ),
    ]
