# Generated by Django 5.0.6 on 2024-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0014_alter_projectpartner_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpartner',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
