# Generated by Django 5.0.6 on 2024-06-12 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_project'),
        ('definitions', '0015_alter_projectpartner_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpartner',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.project'),
        ),
    ]
