# Generated by Django 5.0.6 on 2024-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0016_alter_projectpartner_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
