export enum Industry {
  TECHNOLOGY = 'Technology',
  FINANCE = 'Finance',
  HEALTHCARE = 'Healthcare',
  EDUCATION = 'Education',
  MANUFACTURING = 'Manufacturing',
  RETAIL = 'Retail',
  ENTERTAINMENT = 'Entertainment',
  ENERGY = 'Energy',
  TRANSPORTATION = 'Transportation',
  REAL_ESTATE = 'Real Estate',
  AGRICULTURE = 'Agriculture',
  HOSPITALITY = 'Hospitality',
  TELECOMMUNICATIONS = 'Telecommunications',
  BIOTECHNOLOGY = 'Biotechnology',
  AEROSPACE = 'Aerospace',
  ENVIRONMENTAL = 'Environmental',
  CYBERSECURITY = 'Cybersecurity',
  E_COMMERCE = 'E-Commerce',
  ARTIFICIAL_INTELLIGENCE = 'Artificial Intelligence',
  BLOCKCHAIN = 'Blockchain',
  CONSTRUCTION = 'Construction',
  PHARMACEUTICALS = 'Pharmaceuticals',
  MEDIA = 'Media',
  LOGISTICS = 'Logistics',
  AUTOMOTIVE = 'Automotive',
  FOOD_AND_BEVERAGE = 'Food and Beverage',
  RENEWABLE_ENERGY = 'Renewable Energy',
  FASHION = 'Fashion',
  SPORTS = 'Sports',
  GAMING = 'Gaming',
  LEGAL = 'Legal',
  CONSULTING = 'Consulting',
  TOURISM = 'Tourism',
  INSURANCE = 'Insurance',
  OTHER = 'Other',
}

export const industryIcons = {
  [Industry.TECHNOLOGY]: 'mdi:devices',
  [Industry.FINANCE]: 'mdi:finance',
  [Industry.HEALTHCARE]: 'mdi:hospital-box',
  [Industry.EDUCATION]: 'mdi:school',
  [Industry.MANUFACTURING]: 'mdi:factory',
  [Industry.RETAIL]: 'mdi:store',
  [Industry.ENTERTAINMENT]: 'mdi:theater',
  [Industry.ENERGY]: 'mdi:flash',
  [Industry.TRANSPORTATION]: 'mdi:train-car',
  [Industry.REAL_ESTATE]: 'mdi:home-city',
  [Industry.AGRICULTURE]: 'mdi:tractor',
  [Industry.HOSPITALITY]: 'mdi:room-service',
  [Industry.TELECOMMUNICATIONS]: 'mdi:antenna',
  [Industry.BIOTECHNOLOGY]: 'mdi:dna',
  [Industry.AEROSPACE]: 'mdi:rocket',
  [Industry.ENVIRONMENTAL]: 'mdi:leaf',
  [Industry.CYBERSECURITY]: 'mdi:shield-lock',
  [Industry.E_COMMERCE]: 'mdi:shopping',
  [Industry.ARTIFICIAL_INTELLIGENCE]: 'mdi:brain',
  [Industry.BLOCKCHAIN]: 'mdi:cube-outline',
  [Industry.CONSTRUCTION]: 'mdi:hard-hat',
  [Industry.PHARMACEUTICALS]: 'mdi:pill',
  [Industry.MEDIA]: 'mdi:newspaper',
  [Industry.LOGISTICS]: 'mdi:truck-delivery',
  [Industry.AUTOMOTIVE]: 'mdi:car',
  [Industry.FOOD_AND_BEVERAGE]: 'mdi:food-fork-drink',
  [Industry.RENEWABLE_ENERGY]: 'mdi:solar-power',
  [Industry.FASHION]: 'mdi:hanger',
  [Industry.SPORTS]: 'mdi:basketball',
  [Industry.GAMING]: 'mdi:gamepad-variant',
  [Industry.LEGAL]: 'mdi:scale-balance',
  [Industry.CONSULTING]: 'mdi:account-tie',
  [Industry.TOURISM]: 'mdi:airplane-takeoff',
  [Industry.INSURANCE]: 'mdi:shield-check',
  [Industry.OTHER]: 'mdi:domain',
};

export const getIndustryIcon = (industry: Industry): string =>
  industryIcons[industry] || industryIcons[Industry.OTHER];
