# Generated by Django 5.0.6 on 2024-06-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('document_link', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=50)),
                ('project_id', models.IntegerField()),
            ],
        ),
    ]
