# Generated by Django 5.0.6 on 2024-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_id', models.IntegerField()),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('document_link', models.FileField(upload_to='')),
                ('thought_for_process', models.TextField()),
            ],
        ),
    ]
