# Generated by Django 5.0.6 on 2024-06-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_ideaprocesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('detail', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('idea_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.idea')),
            ],
        ),
    ]
