# Generated by Django 5.0.6 on 2024-07-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_projectdocument_projectstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('staff_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
