# Generated by Django 5.0.6 on 2024-07-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_projectstaff_project_estimated_complete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstaff',
            name='staff_role',
        ),
        migrations.AddField(
            model_name='projectstaff',
            name='staff_role_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
