# Generated by Django 5.0.6 on 2024-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_remove_projectstaff_staff_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('target_investment_date', models.DateField(auto_now_add=True, null=True)),
                ('target_investment_amount', models.IntegerField()),
                ('actual_investment_date', models.DateField(auto_now_add=True, null=True)),
                ('actual_investment_amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_complete_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
