# Generated by Django 5.0.6 on 2024-09-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_remove_idea_project_id_idea_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.IntegerField(choices=[(1, 'Web Site'), (2, 'Junius Flow'), (3, 'Discord'), (4, 'Github'), (5, 'Instagram'), (6, 'Linkedin'), (7, 'X'), (8, 'Facebook')])),
                ('link_address', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business.project')),
            ],
        ),
    ]
