# Generated by Django 5.0.6 on 2024-09-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0011_projectlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideaprocesslog",
            name="document_link",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
