# Generated by Django 5.0.6 on 2024-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0012_alter_ideaprocesslog_document_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="document_link",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
