# Generated by Django 5.0.6 on 2024-09-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_idea_document_link'),
        ('definitions', '0017_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstaff',
            name='staff_role_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='definitions.title'),
        ),
    ]
