version: '3.9'

services:
  frontend:       ## next.js uygulamasi
    image: 471112771661.dkr.ecr.eu-central-1.amazonaws.com/juniusappfront:latest
    pull_policy: always
    container_name: frontend
    volumes:
      - .frontend:/bun/app
    ports:
      - "3000:3000"
    env_file:
      - ./.env




  backend:      ##   python
    image: 471112771661.dkr.ecr.eu-central-1.amazonaws.com/juniusappback:latest
    pull_policy: always
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - /home/ubuntu/junius-app-backend/.env

  nginx:
    container_name: nginx
    #build: ./nginx
    image: nginxjuni
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
  
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot



  certbot:
    #build: ./certbot
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email toptascagri@gmail.com -d app.juniusapps.com --agree-tos