# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/app1.juniusapp.io
cert = /etc/letsencrypt/live/app1.juniusapp.io/cert.pem
privkey = /etc/letsencrypt/live/app1.juniusapp.io/privkey.pem
chain = /etc/letsencrypt/live/app1.juniusapp.io/chain.pem
fullchain = /etc/letsencrypt/live/app1.juniusapp.io/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 00ab9ba4ce8a111a4e1d3967c0afb83a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
