# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/juni.toptas.live
cert = /etc/letsencrypt/live/juni.toptas.live/cert.pem
privkey = /etc/letsencrypt/live/juni.toptas.live/privkey.pem
chain = /etc/letsencrypt/live/juni.toptas.live/chain.pem
fullchain = /etc/letsencrypt/live/juni.toptas.live/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 00ab9ba4ce8a111a4e1d3967c0afb83a
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
juni.toptas.live = /var/www/certbot
